namespace Shared.Domain.Primitives;

// Every entity in every module inherits from this.
// An Entity is an object defined by its identity (Id), not its attributes.
// Two Users with the same name are still different people — their Id is what makes them unique.
public abstract class Entity
{
    // Using Guid so IDs are generated by the app, not the database.
    // Benefit: we can create an entity in memory and know its ID before hitting the DB.
    // This is critical for event-sourcing and domain event publishing.
    public Guid Id { get; init; }

    // Private list — only this entity can raise events.
    // External code reads via the public IReadOnlyList.
    private readonly List<IDomainEvent> _domainEvents = [];

    public IReadOnlyList<IDomainEvent> DomainEvents => _domainEvents.AsReadOnly();

    protected Entity(Guid id)
    {
        Id = id;
    }

    // Called inside domain methods when something meaningful happens.
    // Example: booking.Confirm() calls RaiseDomainEvent(new BookingConfirmedEvent(Id))
    protected void RaiseDomainEvent(IDomainEvent domainEvent)
    {
        _domainEvents.Add(domainEvent);
    }

    // Called by the infrastructure layer after saving to DB and dispatching events.
    // Prevents events from being dispatched twice if SaveChanges is called again.
    public void ClearDomainEvents()
    {
        _domainEvents.Clear();
    }

    // Entities are equal only if they have the same Id and same type.
    public override bool Equals(object? obj)
    {
        if (obj is not Entity other) return false;
        if (ReferenceEquals(this, other)) return true;
        if (GetType() != other.GetType()) return false;
        return Id == other.Id;
    }

    public override int GetHashCode() => Id.GetHashCode();

    public static bool operator ==(Entity? left, Entity? right) =>
        left is not null && right is not null && left.Equals(right);

    public static bool operator !=(Entity? left, Entity? right) => !(left == right);
}
